# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 06:34
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('context', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
            ],
        ),
    ]
